new version of the y-scripts

diff --git a/y-server b/y-server
--- a/y-server
+++ b/y-server
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
-HYBRIS_DIR=`~/dev/branches/sergaks/hybris-decompiler/scripts/hybris-detect.sh`
+HYBRIS_DIR=`y-whereis`
+
+if [ $? -ne 0 ]; then
+	echo "FAILURE"
+	exit 1
+fi
 
 cd "$HYBRIS_DIR" && exec ./hybrisserver.sh "$@"
